### PR TITLE
Gemini CWPT tags 

### PR DESCRIPTION
**Pull request by KerbalKore**
All Gemini parts tagged.

### CODE REVIEW

**Comment by KerbalKore** [comment]
@CobaltWolf @zorg2044  mind taking a look at this? I’m on mobile rn, so I can’t do much.

**Comment by DeltaDizzy** [comment]
You have now encountered the issue i have, namely that there is may more than tags in there. Also it should be targeted to the 1.6 hotfixes branch unless we are too late.

**Comment by KerbalKore** [comment]
@DeltaDizzy I changed the base branch.

**Comment by zorg2044** [comment]
Er this PR is now showing 1300+ changed files.

**Pull request closed without merging**
