### PR TITLE
Added a batch of high fidelity .craft files for Delta family.

### PR DESCRIPTION
**Pull request by JacobB094**
As the selection of .craft files in BDB is currently a bit slim, I decided to have a look at it. The results had been interesting, and they resulted in a large collection of .craft files. I even wrote a nifty user's guide to give users an idea of how these were intended to be used. These are designed to showcase BDB's Delta family, its evolution, including unflown proposals, and sheer flexibility of the parts.

What's in the PR:
119 .craft files for just about every flown or proposed rocket from Delta family, including all ETS variants, as well as some slight extrapolations of mine. They all use SAF fairings.
Flags that I used to replicate real paintjobs on flown rockets and plausible decal layouts on unflown ones. That means they won't load without Conformal Decals.
A huge guide covering every aspect and generation of the Delta family.
Vanguard. Because it doesn't fit anywhere else, and is similar enough to Deltas in overall layout.
Realistic MLP launchpad subassemblies for all this (requires MLP, of course), mostly because I decided to include them in the guide.

I will maintain the .craft files as the mod evolves. This should help new players make heads and tails out of the mod. I'll do the same for other rocket families later on (Titan is next). Feedback appreciated.

### CODE REVIEW

**Comment by zorg2044** [comment]
Really appreciate the effort here. We didn't really want to overload new players with a billion craft files nor did we intend to have dependencies for craft files that don't ship with BDB.

These craft files however would be quite valuable to a certain part of the player so I think its a good idea to have this "advanced" set.

**Comment by Rodg88** [comment]
It does seem like there's a few modules that aren't standard, which cause minor warnings when browsing or loading them. We'd normally use a very stripped down install for making craft files to avoid this. The flags also seem to depend on another mod?

I'd suggest removing FAR, RSE, MJ, Kerbalism, anything that adds modules that aren't required (I even remove waterfall), and reloading and saving them again. You could possibly remove the modules directly from the craft files instead, but that risks them breaking. It will also reduce the size of the craft files as an added bonus.

**Comment by JacobB094** [comment]
I'll probably make a bare minimum install not meant for playing, just for resaving the files created with my main install. As for the flag, you're probably thinking of the mission flag, unless the wrong version of the USAF logo got used. The intended use for those is that people would not load them normally, but use the merge feature to, well, merge them into a payload's .craft file. Then, the US flag would become whatever flag they picked for their space program, since I left that decal as default. If you mean the RealFlags stuff, it's part of the PR, and is meant to go into BDB extras.

TBH, I can just put the US flag in RealFlags, anyway, and ensure the mission flag path points to the RealFlags version. People will likely load the launchers in a regular way, and they'll get a blank flag if it's not done.

I'll take me a while to process 119 .craft files in that manner, but I'll eventually get it done. I do need to alter some early Thors, which used LR-79 NA9 (performance very similar to S-3D), not NA11, but that's relatively quick work.

**Comment by Rodg88** [comment]
Sorry to do it to you, but the stretched Able tank bluedog.DeltaB.Tank is depreciated now, merged into the base Able tank. It appears in the Delta B, C, C1, and D craft files in your PR, so they'll need updating. 

That should be one of the last part merges that may affect launcher craft files at least

**Comment by JacobB094** [comment]
I still have to reexport them on a minimal version, so not a problem, I'll do it then. Also, I'll probably have to replace the tank on either Delta A or Vanguard, those used to be separate, too.

**Comment by JacobB094** [comment]
I cleaned up the modules, updated the flags (turns out CD doesn't work like I think it would, so I threw the US flags in, as well) and replaced the Able tanks, with appropriate changes to the guide.

**Comment by Rodg88** [comment]
Looks like just the delta E1/G, delta III, and IVs need some updates, they have some depreciated parts still - mostly the deployable RL10s or vanguard engines, tho the 7650/7655s need one of the thor extension tanks updated

Delta VIII also relies on Oranges/restock extras parts, but it's probably fine - people will just see it's unloadable if they don't have those.

I've also realized the delta P/K tanks are probably worth merging, but that might require quite a lot of updates haha. I'm happy to swap the tanks around if it helps, tho I guess the PDF may need updating too.

Another thought I've had is if you want to continue updates to your craft collection, we could just include a link in the BDB craft files (and the thread/wiki etc) that links to a GH repo where you keep the craft files, so you're able to add any craft files you want without needing BDB to update, and people can just download them separately? The main advantage is you'd be able to update and add more as much as you want, separately from BDB's slow update cycle. And would save some MB of the main download too lol. If you'd prefer including them in the main download still that's fine too, but I think it's worth considering.

**Comment by JacobB094** [comment]
Delta P/K tank merge will be fine as long as Delta P becomes a variant of Delta K, not the other way around. Seeing as Delta P is used in only a handful of variants, replacing it won't be too hard. In fact, probably easier than sorting out all the advanced Deltas that use the RL10.

Delta VIII shouldn't even be there, it's not quite finished yet (in fact, the ReStock+ part in question is an ore tank I used as a dummy payload). Given that it uses Oranges parts, I don't know when it'll go in. So far, I'm planning another series that would require Photon Corp SSRBs (there's _a lot_ of proposed US designs that strap SSRBs onto other rockets), but jury's still out on what I'll be doing with bigger additions like Oranges. There are some SDLV concepts I'd like to do, but right now I'm focusing on Saturn and Titan.

**Comment by Rodg88** [comment]
The P has to be the base due to tech tree layout, but it's a good idea to update them either way to set the subtype correctly.

**Comment by Rodg88** [comment]
It's likely each craft will still need to be checked as the node positions are slightly different between the P and K, and P is the default config setup (due to tech tree placement, though once unlocked K is the default subtype). The part name that is staying is bluedog_DeltaK_Stage though.

**Comment by JacobB094** [comment]
Well, Satisfactory coming out means I haven't been doing as much KSP as I used to, but I did knock this out. All deprecated parts should be out, and the guide was updated to reflect the changes. I hope that this batch can make it into the next release. Titan is the next one up, but I don't know if I'll finish it in time. With Atlas, I'll probably wait for phase 2 parts.

**Pull request merged**
