### PR TITLE
New RealPlumes based on Plume Party Effects.

### PR DESCRIPTION
**Pull request by zorg2044**
This pull request is a first pass at adding new real plume configs to BDB by converting using PlumeParty FX to recreate the standard BDB plumes in RealPlume. The aim is to preserve the original artistic vision of the mod as far as possible while providing the plume expansion functionality of RealPlume/Smokescreen.

Newly created prefabs will be found in a new prefab folder inside Compatibilit/Realplume. For greater flexibility due to the different animations in Jades effects, each plume component has more individually adjustable parameters available to tweak rather than relying on global settings.

As an additional benefit Most of these new plumes seem a lot more efficient in particle count compared to the standard RealPlume prefabs. 

Currently configed engines

New LR87-5
New LR91-5

F1
J2 (not sea level or Aerospike yet)
LR105
LR89
H1C
H1D
RL10
RL10A4
RL10B2

@jsolson Cobalt has seen some of these but as the config/effects guy would appreciate your feedback!

Preview pics to follow...

### CODE REVIEW

**Comment by zorg2044** [comment]
F1

The turbo exhaust looks slightly different to the stock effect as I had to account for how i interacts with the expanded plume. 
Screenshot 2019-03-26 22 30 38

Screenshot 2019-03-26 22 30 17

Screenshot 2019-03-26 22 31 40

Screenshot 2019-03-26 22 34 50

Screenshot 2019-03-26 22 36 05

Tried to get close to this as far as possible
[https://moon.nasa.gov/system/resources/detail_files/244_detail_S68-27366_orig.jpg](url)

**Comment by zorg2044** [comment]
J2

Screenshot 2019-03-26 19 43 41

Screenshot 2019-03-26 19 44 51

Screenshot 2019-03-26 19 45 07

Screenshot 2019-03-26 19 47 05

Screenshot 2019-03-26 19 48 24

Screenshot 2019-03-26 19 49 29

This is a pretty faithful recreation of the standard plume.

**Comment by zorg2044** [comment]
RL10s

Screenshot 2019-03-27 15 04 20

Screenshot 2019-03-27 15 04 40

Screenshot 2019-03-27 15 04 48

**Comment by zorg2044** [comment]
LR87 (made sure to include the Titan spool up sound in the plume config)

Screenshot 2019-03-26 22 40 55

Screenshot 2019-03-26 22 42 09

Screenshot 2019-03-26 22 42 15

Screenshot 2019-03-27 21 49 27

Some of the "Blaze" effects in lifter engines dont look that great once expanded (especially in screenshots vs animated in game) . Jade has seen this and said he might do something about it. In the meantime it is mainly an issue for the Atlas LR105 sustainer which uses a similar effect. I can also look at using a different effect if this is seen as too much of an issue.

**Comment by zorg2044** [comment]
LR91 - This is the only plume in this PR that references a non plume party effect. The hypergolic vernier prefab uses the same particle used in the RealPlume hypergolic OMS white plume. Can be replaced if Jade makes a dedicated effect.

Screenshot 2019-03-27 22 01 24

Screenshot 2019-03-27 21 57 24

Screenshot 2019-03-27 21 57 37

**Comment by zorg2044** [comment]
The KeroloxLower_Blaze prefab is intended for engines such as the RD180 and Atlas sustainer.
Screenshot 2019-03-27 18 33 25

Screenshot 2019-03-27 18 34 58


Perhaps it might be better to limit max plume expansion to what you get in the upper atmo
Screenshot 2019-03-27 19 01 23

vs this

Screenshot 2019-03-27 19 04 22

**Comment by zorg2044** [comment]
Standard kerolox lower plume 

Currently H1C, H1D and LR89

(I couldnt recreate the specific one used on the LR89 in a nice way when expanded so I gave it this)

Screenshot 2019-03-27 18 44 57

Screenshot 2019-03-27 18 45 17

Screenshot 2019-03-27 18 45 26

Clustered
Screenshot 2019-03-27 18 52 33

Screenshot 2019-03-27 18 53 28

The blaze plume is mostly obscured on Atlas
Screenshot 2019-03-27 19 00 25

Until seperation
Screenshot 2019-03-27 19 01 04

**Comment by zorg2044** [comment]
*doh I've found a way to limit the max particle size. Will update the Kerolox_blaze and LR87 plumes accordingly.

**Comment by jsolson** [comment]
Isn't this interesting. Is it ok to merge or do you have more to do?

About the J2 plume, that fume2 effect was a hacky way to get a bigger plume that didn't overwhelm the nozzle - it's kind of a big plume behind a smaller plume. Is that still necessary with Smokescreen driving things?

The stock effect on the 89-5 is there because I copied it from the same effect on the 89-3, which is multi nozzle, and I can't scale those. Smokescreen doesn't have that limitation so anything that can pass for a dirty gas generator exhaust will do.

**Comment by zorg2044** [comment]
I think its best to wait, I have some ideas on how to fix the blaze plumes. Limiting the max particle size makes it much harder to have an expanded shape so I think its best to fade it out at med-high altitude. That seems more realistic as well

https://www.youtube.com/watch?v=9d8raqfq6oQ

In the case of the LR87 I can hopefully make the blaze fade out nicely with the shock cones and you will be left with a very clean and transparent plume at higher altitidues, appropriate I think for a hypergol.

For RD180, LR105 I did some preliminary testing where I combined the Ibis effect used in the standard kerolox plume with the flamey blaze and then faded out the flame. Needs some tweaks but it could work.

Hehe I realised what you were doing with the J2. I followed the same hack because it made it a little easier the manipulate the shape and its a very lightweight plume particle count wise even with both effects active. I'm kinda learning smokescreen as I go but some of Jades particles are harder to work with than the included effects in realplume when they are divergently animated. Of course thats the reason why they look good.

Sorry I didnt quite follow the last comment, I cant find an LR89-3 in game just Lr89-5 (with upgrades to LR89-7 and RS56 isnt it?), Am I missing something?

I'll try to finalise this set over the weekend hopefully and you can merge, I'll open a new PR for the next set of engines when ready :)

**Comment by jsolson** [comment]
Sorry I get a little dyslexic with my engines sometimes. I meant the verniers on the Titan second stage. There are 4 of them on the Titan 1 engines so I couldn't use a scaled effect, and Jade's got nothing that tiny.

The different plumes on the H1C/D (Sparrow and Ibis I think) were to capture the 4 outer jets around the flamey central column.



They have a unique expansion that is probably impossible though.

**Comment by zorg2044** [comment]
Ah ok gotcha. I think the vernier effect I used here is suitable for now, Ill revisit if Jade makes a smaller one.

I think that epic expansion is possible but only if the lower stage engines are made into a single engine in KSP with 8 nozzles. The Falcon 9 in Tundra exploration is set up as a single engine engine with 9 nozzles and the real plume version done by Nessus has that kind of expansion. Unfortunately Dont think Its doable with 8 individual engines.

image

image

I got some tips from Jade on Sparrow vs Ibis, I'll definitely do an sparrow plume for the H1D, hopefully looks like an easy effect to work with so shouldn't be too much of an issue.

I had a some free time just now and have tried a few tweaks to the LR87

Screenshot 2019-03-28 09 50 47


Screenshot 2019-03-28 09 51 23

I found that doing the fade out rather abruptly is best as its done by lowering the emission value and it looks weird if the emission value is low for too long.

Screenshot 2019-03-28 09 51 54

Screenshot 2019-03-28 09 52 43

**Comment by zorg2044** [comment]
I've replaced the generic kerolox lower with specifically named Ibis and Sparrow plumes. The prefabs and engine configs have been tweaked to get the Saturn 1 looking right.

Screenshot 2019-03-28 12 54 54

Screenshot 2019-03-28 12 55 39

Screenshot 2019-03-28 12 53 27

**Comment by jsolson** [comment]
> I've replaced the generic kerolox lower with specifically named Ibis and Sparrow plumes. The prefabs and engine configs have been tweaked to get the Saturn 1 looking right.

Looks good in game. Distinctive off the pad and suitably impressive when it expands.

**Comment by zorg2044** [comment]
KeroloxBlaze fix

Screenshot 2019-03-28 15 18 45

The flames are visible at liftoff but are faded out and obscured at mid expansion by an Ibis effect

Screenshot 2019-03-28 15 20 16

**Comment by jsolson** [comment]
FWIW the reason for the plume selection on the RD-180 and some others (Delta/Atlas Sustainer) was it would be generally concealed by the solids at launch at could pass for an expanded plume later on. Feel free to use a tighter plume if you think best. I don't object to a little artistic license for some variation though.

https://www.youtube.com/watch?v=ktbQhIySxjc

**Comment by zorg2044** [comment]
@jsolson Have you tried the F1 plume in game? are you happy with it? 

I ditched the smoke on it as it didnt look good trailing the plume when the plume was expanded. 

I had more free time today than I was expecting so managed to make a lot of tweaks. I have one more possible commit to make the LR91 look better in Atmo and then its done unless you have further suggestions or I come across an issue in a final round of testing.

**Comment by jsolson** [comment]
The F1 looks good to me. It's a monster plume. Surprisingly I think I get better framerates with Smokescreen than stock.

Could the smoke trail off in the first 3000-5000 meters? Treat it as a contrail? I was a little unsure about it at first but I think we'll be keeping it in the stock plumes unless there's complaints. It's the only liquid plume we have that smokes.

**Comment by zorg2044** [comment]
Hmm I will give it a try. When the particles are large the transition from high emission to low emission can look janky though. But I feel like I've learned a fair bit since I first looked at the smoke so maybe I can figure something out.

re performance with some plumes like the F1 its using surprisingly few particles when expanded! Because of how Jade animated them they look very good when the emission is turned down for a high altitude translucent look.

**Comment by jsolson** [comment]
I don't know about the smoke. If we kept it the whole burn, is it possible to make it grow with the plume? I forget what it looked like before.

The length of the F1 plume rather rapidly diminishes a little past 30,000 meters, at about 0.02 ATM. It's a bit jarring, is that intentional?

It's a bit hard to tell from the video but it does seem to diminish at the end, and is replaced by contrail. Or the contrail is blocking the view of the plume.
https://www.youtube.com/watch?v=-rM1RA2Jmh8

**Comment by zorg2044** [comment]
Unfortunately the smoke is pretty hard to control as its behaviour is relative to the planet rather than the engine. The faster the rocket goes the thinner the smoke plume becomes. At high speeds it just becomes a thin string. Making the particles bigger and increasing the emission doesnt solve it unfortunately. I can look into integrating an effect from the realplume library if you feel it really needs it. Personally I'm leaning more towards ditching the smoke.

re the transition at 30k, it wasnt a conscious decision, the curves used on the F1 are derived from some other existing plumes I looked at. I think the issue arises from the sheer size of the F1 plume made possible by the shape of the particles used. I'll take another look and see if I can make it a little more gradual but most likely it will mean expanding the plume earlier which probably shouldnt be happening too much before 15km

**Comment by jsolson** [comment]
Don't worry about the high altitude contrail. I can't imagine smoke at mach 3+ will ever look good. That would probably need some whole new effect system. Do what you feel is best with the launch smoke. I will go back and forth on it forever.

**Comment by zorg2044** [comment]
Haha same, I was hoping to offload the smoke decision to you. Ok I went with with my instinct and removed the smoke. I've only commented it out so it can be restored easily.

Ok give this F1 a go. Made the final plume size bigger, started expansion just a little bit earlier and added a few more control points to the curve to make it smoother.

**Comment by jsolson** [comment]
Looks good. Thanks!

**Pull request merged**
