### PR TITLE
Latest updates to several files

### PR DESCRIPTION
**Pull request by rasta013**
Here's the same list I'm PM'ing you with in the forums just in case you miss either one.

Changes

CTT patch updated for most recent parts.  Small balance pass on some parts from previous iteration.
Updated AR patch for both stock and OPM.  Antenna transmission speeds have had a balance pass and the A66 got hit by a giant nerf bat.
A27-C Dish antenna has been added to both AR patches.
Added complete science definitions for the Hydrometer for all stock planets and all situations the experiment can be run.
Added camera science definitions for all 'SrfLandedXXXXX' biomes from Moho to Dres.  Jool system and Eeloo remains for stock solar system.
Balance pass for all three cameras.
	- The low tech camera remains unchanged.
	- The mid-tech camera has been changed to allow up to 6 images to be taken.  All other stats remain unchanged
	- The high-tech camera has been changed significantly.  It now allows unlimited images, mass has been reduced to .025 and the tech node has been moved up to Advanced Science Tech.

### CODE REVIEW

**Comment by CobaltWolf** [comment]
@jsolson halp there's conflicts and I can't merge it

**Comment by rasta013** [comment]
Grrrr....I keep having trouble with getting my sync setup for the fork I upload too.  Will CW be able to resolve it or should I do something on my end to re-issue it?

**Comment by CobaltWolf** [comment]
I have no idea how to resolve it. Let's wait until Jso tells us what to do :P

**Comment by rasta013** [comment]
Ok.  We can kill it and I'll just re-issue if necessary.  I think I may have messed up my sync'd fork again though. :cry:

**Comment by jsolson** [comment]
I have no clue what the conflict might be or what to do.

Edit: Maybe a clue. CW recently had some mystery whole file changes in the AR files that looked like line ends may have changed. We may be having a tug of war between windows and linux style line ends.

**Comment by rasta013** [comment]
Ok.  Can you kill it on your end?  I definitely hosed my sync'd fork so will have to refork again anyway so I could just try that and re-issue the PR.  It may be something I inadvertently did when I killed my sync also.

**Comment by rasta013** [comment]
So that was me killing this PR.  Not seeing that 'Close Pull Request' button is a product of a lack of sleep.  that and never having had to kill one myself.  I'll make my corrections on a new fork and re-issue so that should solve the problems.

**Pull request closed without merging**
