### PR TITLE
Fix MM syntax errors. No operators in HAS blocks allowed.

### PR DESCRIPTION
**Pull request by jmrd98**
@jsolson , easy mistake to make... Hard error to diagnose. Seems to work ok otherwise, but I haven't had a lot of time to test it hardcore.

### CODE REVIEW

**Comment by jsolson** [comment]
Can't be right. I'm on 1.2 with MM 2.7. I'm not setup to test the line in question but...

This works: @PART[bluedog*,Bluedog*]:HAS[@RESOURCE[LqdHydrogen]]
This doesn't: @PART[bluedog*,Bluedog*]:HAS[RESOURCE[LqdHydrogen]]

Is this: HAS[!MODULE[ModuleEngines*]] invalid with the wildcard?

**Comment by jmrd98** [comment]
Indeed, I made a stupid mistake as well... I fixed it so the error cleared, but I didn't actually fix the problem O_o... Hold off on this, let me figure out what is actually going on. My bad.

**Comment by jmrd98** [comment]
This is what i'm getting roared with: 
[ModuleManager] Error - Cannot use operators with insert value: @PART[bluedog*,Bluedog*]:HAS[@RESOURCE[LqdHydrogen],@RESOURCE[Oxidizer],!@RESOURCE[MonoPropellant],!MODULE[ModuleEngines*]]:FOR[Bluedog_DB_0]

You have a good thought with the wildcard, i'm checking that presently. Without the @, it parsed without error, but didn't work correctly. The best/worst kind of fix, gah.

**Comment by jsolson** [comment]
Doh!! It's not the @PART line, it's all this stuff inside:

tank_volume += 
should be
@tank_volume += 

ect, ect

**Comment by jmrd98** [comment]
eeeeyeahh, that'd do it too. Doh! indeed, I missed that one entirely. I still think that you can't do a !@RESOURCE[MonoPropellant], though. Checking both of these things now, but laptop is sluggish having to regenerate the cache.

**Comment by jmrd98** [comment]
Aight, that ought to do it. I'm still unsure of the monoprop test. We want to match things with LF/O or LH2/O that do not have monoprop or engines? Do any parts even have LH2 + MP currently, or is this futureproofing? Adding third commit to restore original syntax to err on the side of caution.

**Comment by jsolson** [comment]
LFO + MP is service modules, and maybe something I'm not thinking of (we have a lot of oddball parts). I'm not sure yet how we want to handle those.

LHO + MP is futureproofing.

**Comment by jsolson** [comment]
Were you able to test this with B9? Does it work?

**Comment by jmrd98** [comment]
Running it right now, the plan seems to have worked; cryotanks is not interfering with the indicated tanks (ie, all of them). Everything has options of LF/O or LH2/O-std. Chalk me up for being wrong on that HAS, I didn't think that would work. TIL.

**Comment by jsolson** [comment]
That's fantastic! Thanks!

**Comment by jsolson** [comment]
You're were right. `!RESOURCE[MonoPropellant]` is correct. `!@RESOURCE[MonoPropellant]` was silently doing nothing - those tanks were being hit as well.

**Pull request merged**
