### PR TITLE
Contracts scidef patch fix

### PR DESCRIPTION
**Pull request by Morphisor244**
Scidef patches to data nodes were not being applied after the name fields got changed to title fields. Added name fields back in while keeping titles, to fix MM patching them.

### CODE REVIEW

**Comment by zorg2044** [comment]
Is there anything specific to the saturn branch in this? Otherwise I'm switching this to master.

**Comment by Morphisor244** [comment]
There isn't, but GitHub was really insistent on including the Saturn branch stuff if I submitted to Master, for some reason. Couldn't get that to go away, sorry.

**Comment by zorg2044** [comment]
Ah you must have based it off of a revamp branch I guess. Nevermind, will just merge as is.

**Comment by Morphisor244** [comment]
I actually tried switching to master before pushing to my local repo, but somehow it just kept the saturn revamp branch stuff in there. - it worked locally, but not when submitting the request from the web repo.

**Pull request merged**
