### PR TITLE
RealPlume to PlumeParty pass 3

### PR DESCRIPTION
**Pull request by zorg2044**
This PR will add plumes for the new Titan engines as they come. 

There are also a couple of small fixes for the RL10 lamp effect size, and I have brought over the plume boundary effect from the RealPlume configs to the kerolox plumes which adds a light smoke/contrail type effect.

UA 1205 has had the standard RealPlume Solid-lower applied.

### CODE REVIEW

**Comment by zorg2044** [comment]
Plume boundary effect added to all the Kerolox lower prefabs. Not sure if needed for the Kerolox vac plume.

Screenshot 2019-04-07 10 52 06

Screenshot 2019-04-07 10 53 00

Screenshot 2019-04-07 10 53 17

Screenshot 2019-04-07 10 53 45

**Comment by zorg2044** [comment]
I've come across a small issue with the UA1205. As currently configured smokescreen does not pick up the angle applied to the thrust transform when the radial version is selected via B9. I used a different effect here for easier checking. Any ideas @jsolson on if its possible with some MM magic to target the   ? If we cant do it then the radial version will have a straight plume, which wouldn't look too bad.

Screenshot 2019-04-11 11 56 55

**Comment by jsolson** [comment]
> Plume boundary effect 

Nice

>I've come across a small issue with the UA1205. As currently configured smokescreen does not pick up the angle applied to the thrust transform when the radial version is selected via B9.

It seems to be working ok with the stock effect. I would have bet it wasn't though, since the stock effect is setup on fxTransform and the switcher is adjusting thrustTransform. I have no clue why it's working. Try using fxTransform.

If you want, take a look at the BDB-Solids-* collection of configs. For those I put everything under a folder in one file. Maybe a BDB-Titan-Engines and BDB-Titan-Solids would be a little easier to maintain than a bunch of different files. That RealPlume folder is a mess.

**Comment by jsolson** [comment]
It's working for me.

~~~
@PART[bluedog_UA1205]:NEEDS[zRealPlume,SmokeScreen]
{
	@MODULE[ModuleEngines*]
	{
		@name = ModuleEnginesFX
		%powerEffectName = Solid-Lower
	}
    PLUME
    {
        name = Solid-Lower
        transformName = thrustTransform
        localRotation = 0,0,0
        localPosition = 0,0,0
        plumePosition = 0,0,0.8
        flarePosition = 0,0,0.7
        fixedScale = 1.3
        energy = 1
        speed = 1
    }
}
~~~

screenshot61

**Comment by zorg2044** [comment]
Huh, I'll take another look.

I can clean up the config files no problem, group them by the same families used for the prefixes.

**Comment by zorg2044** [comment]
Ok the UA1205 seems fine on a fresh install.

**Comment by CobaltWolf** [comment]
The fxTransforms on the SRBs are children of the thrustTransforms

**Comment by zorg2044** [comment]
@jsolson I think this PR is now good to merge. Will open a new one if I spot any issues I've missed or when new engines are added.

Summary of PR
1. Individual config files cleaned up and organised by rocket family
2. Plumes for UA1200 series solids. Working now for both inline and radial  versions.
3. Boundary effect for kerolox lifters
4. Transtage
5. Minor tweaks to some engines and audio fixes that actually work.
6. Changed sound effect for LR91s

**Pull request merged**
