### PR TITLE
Typoed J2s temp engine. Guessing Vac ISP.

### PR DESCRIPTION
**Pull request by jmrd98**
Looks like a copy paste error form the temporary F1A stats.

### CODE REVIEW

**Comment by Araym-KSP** [comment]
... ATTENTION ALSO to "maxthrust"

1.140 (one-point-one-four-zero) is WAY DIFFERENT from the probably value of 1140 (one thousand-one hundred and forty) that should be (??? uhm... maybe a bit too much, for an engine with base line thurst of 258??? even more than an F1???)

**Comment by jmrd98** [comment]
??? Note the operator (*=), for MM, that means take whatever maxThrust was and multiply it by 1.140, for the new value. It should be OK, I think.

**Comment by Araym-KSP** [comment]
Ops... I missed the "operator" LOL... yes, then should be right (it was around 10% more :D )

**Comment by jsolson** [comment]
Thank you :-)

**Pull request merged**
