### PR TITLE
Add reverse control point

### PR DESCRIPTION
**Pull request by SilveiraMarcel**
Add a control point option so the Lunar orbiter can be launched in its real orientation (facing down) more easily. It can be changed in flight by the PAW

### CODE REVIEW

**Comment by SilveiraMarcel** [comment]
Also:
More hullcam support
pretty colored description for SCANsat patch

**Comment by zorg2044** [comment]
Thanks. FYI any time we are appending something to the description it should be done at AFTER[zzzBluedog_DB] so as not be overwritten by the realnames patch. Good idea to have it coloured though, I might do that for the B9 engine switcher notice as well.

**Comment by CobaltWolf** [comment]
How does this work in game? I always just used the Agena as a control point. @SilveiraMarcel @zorg2044

**Comment by SilveiraMarcel** [comment]
> How does this work in game? I always just used the Agena as a control point. @SilveiraMarcel @zorg2044

it adds an option in the Lunar Orbiter Core PAW to change its control point. So it can be launched without the Agena avionics unit, it's not really necessary, but might be nice to have.

**Comment by zorg2044** [comment]
> How does this work in game? I always just used the Agena as a control point. @SilveiraMarcel @zorg2044

The default orientation is still the same as before.

**Comment by CobaltWolf** [comment]
I wasn't sure if it could be changed in flight, I should have clarified that's what I wanted to know

**Pull request merged**
