### PR TITLE
Update to the Extras Folder

### PR DESCRIPTION
**Pull request by Pappystein**
I hope I am doing this right... Modified my Saturn MS file to fix errors and add a MS-1C Flat Bulkhead variant.  deleted E-1 as it was obsolete and added Realname to Titan I impact Science probe.

### CODE REVIEW

**Comment by CobaltWolf** [comment]
@jsolson y'know, just including a MM patch for the RealNames at the bottom of part configs might be the easiest way to do them moving forward. And then we just have to keep up with them as we go for the most part.

**Comment by SilveiraMarcel** [comment]
Adding the MM patches at the end of the part cfg might be a good solution. It works very well for tweakscale and realnames. For realplume it's better to have in a separate cfg.
I think that keeping just RealNames and tweakscale on the part cfg will be better then adding all the extras.

**Comment by jsolson** [comment]
Suppose we add a RealTitle and RealDescription field to each part? Then the realnames patch would just mass copy those over to the title and description fields.

**Comment by CobaltWolf** [comment]
I like that idea, honestly. Whatever encourages us to keep on top of it and treat it like another entry in the checklist for new parts.

**Comment by CobaltWolf** [comment]
Ooooooh, here's an idea, would it be possible to add a checkbox to the difficulty options when starting a new game, similar to how we have the boiloff settings?

**Comment by jsolson** [comment]
No, fake part fields don't get loaded by the game. They're just available in the MM context and the game fills the log with warnings if we don't delete them at the end.

With a part module though... maybe. Title and Description are on the prefab, it might get icky.

~~~
MODULE
{
    name = ModuleRealNames
    title = Rocketdyne F1 Liquid Fuel Engine
    description = First stage engine for the Saturn V rocket
}
~~~

**Comment by jmrd98** [comment]
Another option is this variant of MM syntax that I rarely see used (from their examples):
PART:NEEDS[RealFuels|ModularFuelSystem]
{
    name = myPartName
    description:NEEDS[RealFuels&!ModularFuelSystem] = This part is used in real fuels
    description:NEEDS[ModularFuelSystem&!RealFuels] = This part is used in modular fuel system
}
The patch could be at the bottom of the respective config. The enabling condition would be the presence of the realnames cfg from the extras folder. It would just need to be a noop with a FOR:[RealNames] in it to activate the relevant code.

**Comment by jsolson** [comment]
I want to avoid this:
~~~
PART
{
   name = xyz
   1000 lines...
}
@PART[xyz]:NEEDS[RealNames]
{
   set name and title
}
~~~
because changing the part name in the patch at the bottom will be forgotten/messed up.

This is cleaner:
~~~
PART
{
   name = xyz
   RealTitle = Rocketdyne F1 Liquid Fuel Engine
   RealDescription = First stage engine for the Saturn V rocket
}
~~~
Then one global patch (ok, two) that's enabled by a FOR[RealNames] somewhere:
~~~
@PART[bluedog*]:HAS[#RealTitle]:NEEDS[RealNames]
{
   @title = RealTitle
}
@PART[bluedog*]:HAS[#RealDescription]:NEEDS[RealNames]
{
   @description = RealDescription
}
~~~
If we want a checkbox in options, the the part module approach above instead. If it works.

TweakScale we could do like this:
~~~
PART
{
   name = xyz
   stuff

   MODULE:NEEDS[TweakScale]
   {
      tweakscale stuff
   }
}
~~~

**Comment by jmrd98** [comment]
I’m not sure I see a big difference between mine and your “cleaner” one, but that also means there isn’t a strong preference either way. 

I also blanched at the “patch at the bottom”, which is why I made my edit.

Is there an occasion when a real name but not a real description would come up? A two patch pass is probably more secure as you have it.

**Comment by jsolson** [comment]
>I’m not sure I see a big difference

The difference is when people copy/paste they will overlook setting the correct part name in yours. There's no @PART[this file] mechanism.

**Pull request merged**
