### PR TITLE
Moved Titan I decoupler to node with the rest of the parts.

### LINKED ISSUE #189: Tech tree placement issues
The Prometheus I parts are all in General Rocketry, except for the 1.5m Decoupler, which is in General construction. Is this intentional? It seems like all the essential parts for a particular rocket should be in the same node, though not necessarily the upgrades.

### PR DESCRIPTION
**Pull request by IronCretin**
Fixes #189

### CODE REVIEW

**Comment by IronCretin** [comment]
How do I remove the extra commits from the pull?

**Comment by jsolson** [comment]
I usually delete my branches after a pull. Keeping them in synch with master is a pain.

**Comment by IronCretin** [comment]
How do I do that? These are from my master branch. Do I just delete that?

**Comment by jsolson** [comment]
Sorry, I said branch, I meant fork.

You seem to be keeping your fork up to date with master which is more than I ever accomplished, which I why I delete them after a pull. I don't know why all that extra stuff is showing up. I would just delete the fork and start fresh, they're free after all.

**Pull request merged**
