### PR TITLE
CRP support and improved USI support

### PR DESCRIPTION
**Pull request by SilveiraMarcel**
*Added a patch to add ModuleResourceScanner to some science parts if the user has the CommunityResourcePack.
*Added a patch to replace the monoPropellant fuel cells with Hydrogen-Oxygen ones if the user has CommunityResourcePack and does not have TAC-LS
*Added a custom B9tankType to deliver Machinery

### CODE REVIEW

**Comment by CobaltWolf** [comment]
Do we want to have the fuel cell patch? That would add additional mass and complexity wouldn't it?

**Comment by Gordon-Dry** [comment]
As a Kerbalism user I like them.

**Comment by CobaltWolf** [comment]
@Gordon-Dry ok but I don't know if the majority of CRP users (that is, all users... especially since BDB is dependent on it!) would like it, and that's what triggers that MM patch.

In general I don't really know what affect life support has on the parts and how it affects their balance, since I don't have time to test and balance that stuff.

**Comment by SilveiraMarcel** [comment]
> Do we want to have the fuel cell patch? That would add additional mass and complexity wouldn't it?
The final mass stays the same, the patch reduces the part's dry mass by the same amount as it would increase due to the resources. It's a zero sum process.

> [...] ok but I don't know if the majority of CRP users [...] would like it
Honestly I don't know, Some might like it, some might dislike it but certainly there is a niche for the fuel cells

**Comment by Gordon-Dry** [comment]
Well, the patch got NEEDS[!TacLifeSupport] in it, so why not?

**Comment by SilveiraMarcel** [comment]
> Well, the patch got NEEDS[!TacLifeSupport] in it, so why not?

That is added to avoid conflict with the TAC-LS patch already in the release

**Comment by jsolson** [comment]
USI stuff OK
Sensors OK. It can go in the part.cfg since CRP is stock for our purposes, but this way is fine for now.

Fuel Cells Soft No. Hasn't been discussed.
Increasing the EC maxAmount is a unnecessary. That gives the Block II almost twice the storage of the all battery powered Block III. I don't know why that's there.
The LEM Ascent Module has no fuel cell. It's all battery power.
No need for a base part mass adjustment, you can offset the additional mass with less MP. Both service modules have excessive MP storage for the fuel cell.
There's no real energy consumer other than antennas in stock, so this is mostly gee-whiz. Does that outweigh the additional two resources (menu clutter).
I'd need to see what other mods are doing with this if there are any (SSTU seems likely) so we can compare consumption/generation amounts and not upset the apple cart.

**Pull request merged**
