### PR TITLE
Update bluedog_Saturn_S1F_Tankage.cfg

### PR DESCRIPTION
**Pull request by Araym-KSP**
Updated mass, cost, name and fuel load as TEST2 discussion

### CODE REVIEW

**Comment by CobaltWolf** [comment]
@jsolson does this conflict with your balloon tank fix for the S1F?

**Comment by jsolson** [comment]
>does this conflict with your balloon tank fix for the S1F?

Yes, this commit is no good for a balloon tank.

It's got me scratching my head though, why did we reduce the fuel on these tanks? By the measurements the fuel for this tank should be 22.1K not 17.5K, and the S1E should be 17.6K not 14K.

If there's some way to search past issues I can't find it.

**Comment by CobaltWolf** [comment]
I don't know, but I'm all for increasing the fuel amounts... esp. if it means we can also buff the S1.

**Comment by jsolson** [comment]
>increasing the fuel amounts
We'll do that.

>buff the S1
It's fine.

**Comment by CobaltWolf** [comment]
Saturn 1B is still underperforming last I checked. If we are still assuming that the BDB stuff should work in a roughly 2.5x system, it's one of the few LVs that doesn't perform as expected. I tried trimming some weight from the Apollo to compensate, in addition to all the weight removed from the S-I and S-IVB back in December.

**Comment by jsolson** [comment]
I just tested a fully loaded Apollo/S-IVB/S-I. It lept off the pad (1.4+ TWR) and easily made a 200km orbit with over 1000 dv to spare in a 3X system.

**Comment by CobaltWolf** [comment]
Oh, that reminds me, the has been showing my dV for my upper stages as very low (100-200m/s), any idea?

And can you send me a craft file for that?

**Pull request closed without merging**
