### PR TITLE
Plume Party to RealPlume pass 4

### PR DESCRIPTION
**Pull request by zorg2044**
All 4 new single mount LR87s get plumes, Vanguard vernier reverted to original real plume (missed this out earlier)

Before closing this PR I would still like to revisit F1 again as I think it can still look a bit too odd when fps is suboptimal.

### CODE REVIEW

**Comment by CobaltWolf** [comment]
Jade commented on my last stream that something we were doing with the Plume Party plumes was wrong and it made them get way worse FPS than they should. I don't remember what it was tho.

**Comment by zorg2044** [comment]
Oh ok, I'll follow up with Jade.

**Comment by zorg2044** [comment]
@CobaltWolf I spoke to Jade about this. His comment was more to do with the stock plumes, he suspected based on pics that maybe the particle numbers, lifetimes and speed are quite high to get the long plumes for lifter engines.

For these realplumes I am benchmarking against the old realplume configs and these new ones use fewer particles for the most part so performance is actually better.

**Comment by CobaltWolf** [comment]
Jso seems indisposed with real life stuff - is there any way I could ask you to take a look at the worst of the stock PP plumes? I'm assuming the F-1 is the worst offender but it might be an issue that affects most of them.

**Comment by jsolson** [comment]
I lowered the partial counts a while back. Jade setup the current F1 plume.

**Comment by zorg2044** [comment]
Added IUS plumes, made a couple of positioning fixes to Peacekeeper 2nd and 3rd stage.

**Comment by CobaltWolf** [comment]
Well then Jade can suck it :P

**Comment by zorg2044** [comment]
SRMUs done. Some tweaks to Atlas LR89 and F1.

**Comment by zorg2044** [comment]
The LR87 plume has been completely rebuilt now. It looks mostly the same on the surface but it has an interesting throttle response now where both the plume together with the relative position of the shock cones will move and stretch. The shock cones also now fade out one by one starting from the last one and ending with the one closest to the engine bell. The appearance of the plume is also nicer in the 20-30 fps range.

The plume expansion has been reworked and the vacuum appearance is much nicer. I overlaid the LR91 stream effect at high altitudes.

Based on the work Nessus did for Tundra exploration, the Atmosphere and Throttle keys are defined in a seperate CFG and the plume prefabs now reference those keys which makes it much easier to build and adjust plumes. It also leaves open the possibility of re-configuring all plumes that refer those keys for RSS/RO by patching those keys instead of rebuilding the plumes from scratch (if some kind soul ever gets to it :P )

As and when possible, I will slowly convert the prefabs for the other plumes into this new system. Hopefully it won't take too long as the basic appearance has already been set up.

Finally the individual particle effects in the prefab are defined relative to only a few base values. Meaning its no longer necessary to define energy, speed and emission for each particle when setting up each engine the way I did initially. Should make configuring new engines much simpler for anyone else who may contribute in the future.

Screenshot 2019-06-30 13 14 54

Sea level on left, fully expanded on right

Screenshot 2019-06-30 13 11 59

Flame effect seen shortly after take off but before proper expansion begins. Shrunken vacuum plume on right.

**Comment by zorg2044** [comment]
LR91-3 "stock" and realplume done. 

I've adjusted the stock vernier effect to the right position and replaced the main one with Jades kerolox FX.

I think this PR can be closed. I'll open a new one for the LR87-3 and any other tweaks I do in the meantime.

Not sure where the conflict is coming from, this PR is based on a fork thats a little behind the current dev branch. But the LR91-3 cfg file is the same file you uploaded yesterday with just the effects changed. 

These are the two nodes within EFFECTS I edited
```
                running_engine
		{
			AUDIO
			{
				channel = Ship
				clip = Bluedog_DB/Sounds/KW/sound_altloop
				volume = 0.0 0.0
				volume = 0.01 0.1
				volume = 1.0 1.0
				pitch = 0.0 1
				pitch = 1.0 1
				loop = true
			}

			MODEL_MULTI_PARTICLE
			{
				name = fume
				modelName = Bluedog_DB/FX/PlumeParty/Engines/Generic/keroOlympusBlaze
				transformName = thrustTransform
				emission = 0.0 0.0
				emission = 0.01 0.1
				emission = 1.0 1.0
				speed = 0.0 2.0
				speed = 1.0 2.0
				energy = 0.0 0.5
				energy = 1.0 1.0
				localScale = 0.8,0.8,0.8
				localPosition = 0,0,0
			}

			MODEL_MULTI_PARTICLE
			{
				name = spark
				modelName = Bluedog_DB/FX/PlumeParty/Engines/Generic/keroOlympusLamp
				transformName = thrustTransform
				emission = 0.0 0.0
				emission = 0.01 0.1
				emission = 1.0 2.0
				speed = 0.0 1.0
				speed = 1.0 1.0
				energy = 0.0 1.0
				energy = 1.0 1.0
				localScale = 0.8,0.8,0.8
				localPosition = 0,0,0
			}
		}
		running_vernier
		{
			AUDIO
			{
				channel = Ship
				clip = Bluedog_DB/Sounds/KW/sound_altloop
				volume = 0.0 0.0
				volume = 0.01 0.1
				volume = 1.0 0.5
				pitch = 0.0 1
				pitch = 1.0 1
				loop = true
			}

			MODEL_MULTI_PARTICLE
			{
				modelName = Squad/FX/LES_Thruster
				transformName = vernierTransform
				emission = 0.0 0.0
				emission = 0.001 0.2
				emission = 1.0 0.5
				speed = 0.0 0.4
				speed = 1.0 0.7
				energy = 0.0 0.25
				energy = 1.0 0.5
				localOffset = 0,0,-0.5
			}

		}
```

**Comment by jsolson** [comment]
>Not sure where the conflict is coming from

Looks like just whitespace. Good job as always. Thanks!!

**Pull request merged**
