### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by tinygrox**
It took me five days. Localized parts and fields only.
The `ScienceDefs.cfg` still in progress.

### CODE REVIEW

**Comment by zorg2044** [comment]
Hi @tinygrox , this is a bit awkward but we don't really have a desire to add localisation fields to everything unless we have a firm commitment from people to fully do the localisation for various other languages. Simply having the fields while having only eng localisation just makes extra work.

Its also worth noting that you have targeted the development branch while the current actively developed branch is v1.7-development which is now several hundred commits ahead. 

It would be really advisable in the future to first contact the authors before doing such a far reaching PR :/

**Comment by tinygrox** [comment]
I collapsed.
:(

**Comment by tinygrox** [comment]
@zorg2044 What if I provide the Chinese language? 
Look, I just want your mod to support the language of my country , cuz this mod are so great!

**Comment by zorg2044** [comment]
@tinygrox We do really appreciate your enthusiasm for BDB! However maybe we can revisit this discussion in a few months time after BDB 1.7 is out? 

BDB 1.7 is one of the biggest updates ever for BDB with a lot of new parts being added and a lot of old parts being revamped. Things are still changing very regularly (even the science experiments and sciencedefs) and I think doing this right now could get in the way. After BDB 1.7's initial release most of the revamps will be complete and a localisation project might be worthwhile at that point.

**Comment by tinygrox** [comment]
All right.
Remember to let me know then
I'll be back. :)

**Pull request closed without merging**
