### PR TITLE
Decaying RTGs Patch

### PR DESCRIPTION
**Pull request by Clamp-o-Tron**
Based on the optional NF Electrical patch, requires NF Electrical to work

### CODE REVIEW

**Comment by biohazard15** [comment]
You forgot the brackets - {} - after !MODULE[ModuleGenerator]. This leads to RTGs having both stock and NFE generators.

**Comment by Clamp-o-Tron** [comment]
Oops, my bad. I basically threw this together the instant I saw the RTGs.

**Comment by zorg2044** [comment]
@Clamp-o-Tron does this make the RTGs decay by default (when NFE is detected?). Asking because decaying RTGs in NFE itself is an optional extra.

**Comment by Clamp-o-Tron** [comment]
It's in extras, so it only should do that if intentionally installed. The folder name and comments are pretty clear as to what it does.

IDK for EasyMode, but every single RTG patched by DecayingRTGs has that = True. Probably prevents power outputs from going beneath 10% or something.

**Comment by zorg2044** [comment]
> It's in extras, so it only should do that if intentionally installed. The folder name and comments are pretty clear as to what it does.
> 
> IDK for EasyMode, but every single RTG patched by DecayingRTGs has that = True. Probably prevents power outputs from going beneath 10% or something.

Oh I totally missed that it was in extras :P

**Pull request merged**
