### PR TITLE
more mariner stuff

### PR DESCRIPTION
**Pull request by SilveiraMarcel**
- three new parts IF the user has USI life support, just adapted the MOL 1.5m and 1.875m "room" parts so they behave as a logistic module. In the future I might change it to work with SSPX

- Mariner sensors and scanners

- adds more nodes to OGO probe (kinda like the vanilla rover body) and creates an empty version for ballast because reasons

### CODE REVIEW

**Comment by zorg2044** [comment]
@SilveiraMarcel thanks for these! Couple of notes though:

I think the OGO stuff is better suited to BDB extras

Should the radiometer have a low res scansat module? I don't know that an instrument like that is reasonable for mapping especially since we have a dedicated radar altimeter part.

Dont think the Gamma Ray spectroscope needs the biome scanner module either, unless the IRL use case closely matches that kind of use. Im not too familiar :P But otherwise its overlapping unnecessarily with the TV camera.

**Comment by SilveiraMarcel** [comment]
yeah, I also think that the OGO ballast is better suited as an extra so I agree with that. But the extra attachment nodes can be useful to make small rovers and such.
I'm also divided on the radiometer, maybe it should be used as a low resolution while the radio altimeter should be used as an high resolution radar.
the biome scanner in the gamma ray spectroscope isn't for mapping biomes, is used the get the water distribution in that biome.

**Comment by DeltaDizzy** [comment]
> I'm also divided on the radiometer, maybe it should be used as a low resolution while the radio altimeter should be used as an high resolution radar.

Wasn't the Mariner radiometer used for determining temperature and water vapor content?

**Comment by CobaltWolf** [comment]
OGO is getting remade soon anyways (the models are all done just hasn't been a priority to texture)

The radiometer shouldn't be used for altimetry, it's a completely different instrument.

The radar altimeter should be a low res scanner, I think. Maybe? idk, there is/was supposed to be a big update to SCANsat but idk if it's DOA or what. https://github.com/ChrisAdderley/SCANsat/issues/1

Indeed the gamma ray spectrometer was used to try and find water. Of course, no actual useful data was obtained.

**Comment by zorg2044** [comment]
regardless of whether that proposed update to Scansat is coming any time soon, Radar Altimetry is the default instrument for Scansat low res terrrain data. High res is via Synthetic Aperture Radar so the Radar Altimetry instrument should def remain low res.

**Comment by zorg2044** [comment]
For BDB high res altimetry the only things that come to mind suitable for high res altimetry would be the MOL KH10 and the upcoming Corona.

**Comment by zorg2044** [comment]
Looks like the MOL camera currently has biome scanning right now but I think I'll change it to high res altimetry when I get a moment.

**Comment by CobaltWolf** [comment]
what's the deal with these

**Comment by CobaltWolf** [comment]
pongsst

**Pull request merged**
