### PR TITLE
VariantThemes Missing

### PR DESCRIPTION
**Pull request by 7ranceaddic7**
This file is created from variant theme info already know.

### CODE REVIEW

**Comment by DeltaDizzy** [comment]
BDB doesn't use the stock variant system, so that won't do anything.

**Comment by 7ranceaddic7** [comment]
They are used in this BDB config.

Gamedata/Bluedog_DB/Compatibility/ProceduralFairings/bdb_pf_side.cfg

**Comment by jsolson** [comment]
@7ranceaddic7 this has conflicts and can't be merged because it's from your master branch to our development branch. You need to push your changes to your development branch and then submit the PR to this development branch.

**Comment by 7ranceaddic7** [comment]
@jsolson I think I've done what is necessary.  But, failing that, I've invited you so you can do what is needed.

**Pull request closed without merging**
