### PR TITLE
Plume Party to RealPlume pass 5

### PR DESCRIPTION
**Pull request by zorg2044**
New Readme file with guide to the plume configs.

Kerolox lower blaze prefab overhauled significantly and updated to use new key variables.

The blaze prefab seems to work well with upper stages in fully expanded form. Using it for kerolox upper stages to avoid duplication of effort (vega etc) at least for now :P

New plume party based kerolox vernier using Eagle effect uploaded with last PR replaces RealPlume one still being used.

LR87-AJ3 configured.

LT91-AJ3, Lr101, Lr105, RD180, RS27, 45K, 6k, S3D , Vega, vanguard 405,  all updated. 

Needs some testing before merging since a lot of engines were configured.

### CODE REVIEW

**Comment by zorg2044** [comment]
Screenshot 2019-07-07 18 27 03

Screenshot 2019-07-07 18 28 48

**Comment by zorg2044** [comment]
Since I opened this PR there has been a big update to Smokescreen with all new decluster and emitOnUpdate options which can drastically improve the look of plumes by preventing the sort of clumping that you see at high particle speed/energy or even at low PC framerates! I will probably be revisiting a few plumes to add these options to smooth things out in some cases, and in others to take advantage of it to create large plumes. This could be the solution to the problems I've been having with F1 since the beginning.

**Comment by zorg2044** [comment]
These screenshots were taken on my full career install, heavily modded. Saturn V off the pad gets around 18fps and yet the plume now doesnt break up and looks good!

screenshot1507

screenshot1508

I think this is the fourth rebuild of the f1 plume :P But this engine deserves the effort.

screenshot1512

screenshot1514

**Comment by zorg2044** [comment]
New Hydrolox upper plume. Now much better at lower altitudes so your J2 wont look garbage when used from mid altitudes. Instead of trying to manipulate the Fume effect in ways it doesnt want to (since its so highly divergent) using a convergent Stream effect from sea level and fading in the Fume into the core of at at higher altitudes. Bonus shuttle style single shock cone at SL too.

screenshot1559

screenshot1560

screenshot1561

screenshot1564

The new SL cryo plume is the same thing but with blaze effect between lift off and initial plume expansion start and less underexpansion of the stream effect at SL.

Screenshot 2019-07-08 15 50 44

**Comment by zorg2044** [comment]
Hypergolic upper red and yellow redone. Old Upper red fizzle and and upper red now consolidated into a single one.

These two plumes are built using the same method as the Cryo plume. However they both use the same jet engine overlay stream effect so they will look identical at SL. I dont consider this a major issue as these engines are unusable at SL. They will also be a lot thinner due to the power drop compared to the pic below at SL. As with the Cryo plumes, the fume effects will fade in at higher atmo.

The disgusting throttle response of the yellow plume has also been fixed. It actually got longer at low throttle before :P

Screenshot 2019-07-08 18 28 05

Screenshot 2019-07-08 18 28 36

**Comment by CobaltWolf** [comment]
Sweet!

**Comment by zorg2044** [comment]
All new J2T plume with some custom made to order FX from Jade :)

screenshot1657

Its got that distinctive aerospike pinch after the nozzle at sea level.

screenshot1658

built using two plume segments, the first short segment used to make the pinch expands as you ascend while the longer plume shifts inward towards the nozzle and forms a distinct aerospike core.

screenshot1661

The core remains distinct throughout ascent right up towards the final vacuum shape when both the core and the envelope are highly expanded.

screenshot1662

The overall look remains inspired by that one test firing picture which seems to show something ablating or a particularly fuel rich mixture being used. So this plume will be orange unlike all the other Lh2 plumes.

screenshot1663

Link to video

https://www.youtube.com/watch?v=pdyClUn4MIY&feature=youtu.be

**Comment by zorg2044** [comment]
Also all new "complex" plume for the hypergolic LR87 sea level engines. Uses multiple plume sub segments to create realistic shock cones. Theres some interesting throttle behaviour too although I guess most users might not see it! 

the flame effect now needs to be there from the beginning as it helps smooth out the transitions from the final sub segment. The plume sub segments that make up the shock cones each fade out one by one, the first one fades out together with the flames. 

Still needs some more fine tuning. Transition of the final subsegment is a little odd and need to match up stream and flame length at lift off.

Once the sea level effects disappear its identical to the most recent revision of the Lr87 plume. Max particles I saw was around 600, ie 300 per plume so thats still really efficient particle count wise despite there being 9 separate active effects at life off.

screenshot1664

screenshot1666

screenshot1667

Throttle behaviour compared with current

https://www.youtube.com/watch?v=znhtKZ3XJLY

Inflight expansion vs current

https://www.youtube.com/watch?v=OXR5JYZIL2A

**Pull request merged**
