### PR TITLE
Pr/200

### PR DESCRIPTION
**Pull request by jsolson**

### CODE REVIEW

**Comment by jmrd98** [comment]
beat me to it... thanks much.

**Comment by jsolson** [comment]
This PR was actually a failed attempt to resolve it. I ended up on the command line, with my fingers crossed typing commands from the "how to resolve" page with no idea what I was doing :-)

**Comment by jmrd98** [comment]
If we want the original, I can get it, i'm pretty sure. I just quit cause I thought you had it :p I am right there with you on git merge failures, grumble grumble.

**Comment by jsolson** [comment]
I'm pretty sure got it all. I think the submitter is expected to resolve their own conflicts. I merged his changes into my local copy and then merged that into master. I don't see how I can modify the original pull request and then merge that. Git is so arcane... Locally I pull and commit/push, and merge other peoples PR's through the website, beyond that I'm lost.

**Comment by jmrd98** [comment]
I had to look it up: Locally you do a git pull (Their URL) (The branch they want to merge) and it will make a new branch (of that name) in YOUR tree with their commits. Then the joy of merging against master begins. Finally, merge your commit of their branch merges and commit that and push, PR, approve... Bah Humbug. The tools are powerful, but the usability is not always high or obvious.

**Pull request closed without merging**
