### PR TITLE
Compatibility

### PR DESCRIPTION
**Pull request by IronCretin**
Added community category kit support and fixed the usi compatibility.

### CODE REVIEW

**Comment by jsolson** [comment]
According to the discussion in issue #238 the USI-LS patch is disabled because it doesn't work. I don't use it so I can't say. The supply.cfg file sets up supplies for the cargo containers, and so does the disabled file so the two definitely conflict.

**Comment by IronCretin** [comment]
I've reverted that change, how about now?

**Comment by jsolson** [comment]
Approved! Too me some digging to figure out what the point of the tags is. Is there a proper release thread for community category kit somewhere? My google-fu is failing me.

**Comment by IronCretin** [comment]
No release thread yet. Documentation is on the [wiki](https://github.com/BobPalmer/CommunityCategoryKit/wiki). Basically, the plugin uses tags to determine what custom categories to put the parts in.

**Pull request merged**
