### PR TITLE
SAS update

### PR DESCRIPTION
**Pull request by meirumeiru**
SAS in probe cores is now only available after researching specific technologies

### CODE REVIEW

**Comment by jsolson** [comment]
I like.

My initial impression is it's a bit deep in the tech tree, but we can go with this if you want. MechJeb would give you all the control options with SmartASS at flightControl.

**Comment by meirumeiru** [comment]
I added an additional bugfix (all experiments are inactive otherwise)...

about the positions of those upgrades... I don't know if they are good... I had to put them somewhere :-)

**Comment by CobaltWolf** [comment]
What tier is Flight Control? Not that far in is it? I say merge it in (and thank you @meirumeiru for the bug fix), we'll have to wrangle some beta testers before the next release anyways

**Comment by jsolson** [comment]
The way he has it is:
Tech Level 0 Start - nothing
Tech 1 Engineering 101 - SAS level 0 (attitude) 5 point insta ugrade
Tech 4 Miniturization - SAS level 1 (pro-retrograde) 90 points
Tech 6 Unmanned - SAS Level 2 (radial, etc) 300 points
Tech 7 Adv Unmanned - SAS level 3 (target tracking) 550 points

If I were doing it I'd do:
Tech Level 0 Start - nothing
Tech 1 Engineering 101 - SAS level 0
Tech 3 Flight Control - SAS level 1
Tech 4 Adv Flight Control - SAS level 2
Tech 5 Spec Control - SAS level 3

Full disclosure, I'm the sort who in a career game cheats to the 2nd level tracking station and has all MechJeb options enabled at Start.

I think we can merge as is. I think Miniaturization is too deep for progade retorgrade, but I don't see a better place to put it using that deeper path.

**Comment by CobaltWolf** [comment]
I favor the faster progression, since by the time you get to tier 5 you are starting to unlock stuff like automated resupply for stations.

**Comment by CobaltWolf** [comment]
Erm, well back up. So perhaps have the larger cores (ie, the avionics cores but not the probes) use the faster progression, while the probes keep what @meirumeiru has established? A larger vessel can more reasonably be expected to be capable of more control, while miniaturizing the control hardware is harder

**Pull request merged**
