### PR TITLE
Patch 4

### PR DESCRIPTION
**Pull request by Araym-KSP**
FASA Launch Clamp updated to be bound in BDB.

- changed (inside cfg) all the names with an addition of "BDB_", just to avoid KSP conflicts in case anyone had the original one...
- updated MODEL folder paths to reflect changed position inside BDB directories
- nothing else done (models, textures, balancement/placement in techtree, all the cfg syntax left as original)

### CODE REVIEW

**Comment by CobaltWolf** [comment]
@jsolson these are the FASA Launch Clamps. Can you do some checks on them tonight if you get a chance?

**Comment by jsolson** [comment]
Are these not still available separately? I really don't think we should be bundling if they are. Or at least not relocating them. It will cause confusion.

**Comment by CobaltWolf** [comment]
As far as I can tell, the separate download is no longer maintained. And I plan on making some modifications to the textures

**Comment by jsolson** [comment]
Ok good.

@Araym-KSP are there any bugs or oddities in these we can look into fixing? The only one I've ever really used is the Atlas clamp. I seem to recall the Mercury clamp being a bit troublesome.

**Comment by Araym-KSP** [comment]
@jsolson 
Uhm... I haven't used them a lot in 1.2 (basically like all the things, that I just using pre-releases barelly)... as far I can remember, the only (sometime) issue I saw (still in 1.1.3, so it should be checked in 1.2) was the "Launch Tower" (the one to move kerbals up and down to load the capsule above the rocket):

 sometime, when activated to retract the walkway, it shakes a lot itself, and put some "push" to the rocket too.
I always guessed thet the walkway collider itself (to let the kerbals reach the pod on a rocket) it is a bit too long, intersecting those on the rocket. In fact when I saw the issue, I always moved it with the gizmos a bit away from the rocket itself and the problem generally mitigates.
Related it seems that it does not like to be clipped to other things/other launchclamps even in the "tower" part itself. It's surelly the one that needs some "attentions/modifications" first.


For the issues with the redstone clamps (those to put under an engine/rocket), it used to be buggy (htey didn't released the rocket correctly) but (if I remember correctly) it was someway corrected. Up to now I never had particulary problems...

**Pull request merged**
