### PR TITLE
Added note about autostrut to LES

### PR DESCRIPTION
**Pull request by IronCretin**
Every day, someone asks in the thread how to stop it wobbling. Now we
can laugh at them for not reading the instructions.

### CODE REVIEW

**Comment by jsolson** [comment]
This and omg so many parts! We need an faq.

**Comment by IronCretin** [comment]
Is the wiki editable? We could put it there.

**Comment by IronCretin** [comment]
It's not, but you could make it publically editable: https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by jsolson** [comment]
> make it publically editable: https://help.github.com/articles/changing-access-permissions-for-wikis/

@CobaltWolf please adjust the Wiki permissions.

**Pull request merged**
