### PR TITLE
PlumeParty to realplume pass 2

### PR DESCRIPTION
**Pull request by zorg2044**
@jsolson This is still WIP but I thought you can keep track and review in the meantime if you wish.

Audio fixes for some missing engage sounds
Volume adjustment nodes to some engine configs using scaled plumes

Engines on this round so far
All AJ10s (Apollo, Abel, Delta,Transtage)
Delta RS27 
Thor LR79
Vanguard 1st stage + 3 chamber version
Vega
Agena A, D

### CODE REVIEW

**Comment by zorg2044** [comment]
Screenshot 2019-03-30 23 31 18

Screenshot 2019-03-30 23 31 48

Agena D

**Comment by zorg2044** [comment]
Screenshot 2019-03-31 01 46 30 

The divergent stream effect is very difficult to straighten out at sea level (as seen on the LMDE and LMAE). I actually used a sea level stream effect on the SPS. But the divergent vac stream effect does look nicer when expanded... do you think the compromise is worth it to prioritize better looks in vacuum for these dedicated vac engines?

Screenshot 2019-03-31 01 47 59

Screenshot 2019-03-31 01 48 28

Btw the LR87 plume has had the atmo curve adjusted. I will do a review of all the curves including the earlier prefabs before finalizing this PR.

**Comment by zorg2044** [comment]
Hi @jsolson what do you think of following this curve for plume expansion?

ATMO Curve for Kerbin at normal 2.5x rescale using SD and Galileo's Rescale! unmodified

~~~
Density   Alt(2.5x)   Atm kN/m2     Notes for lifter engines
1.0       0m          99
0.8       5000m       50
0.6       9000m       24            Minor expansion to this point
0.5       11,900m     17            Noticeable plume expansion begins
0.35      15,250m     8
0.2       20,000m     3.58          Maximum size
0.10      28,000m     0.85          Plume begins shortening
0.05      35,500m     0.27          Plume considerably shorter and approaching vacuum shape
0.01      58,000m     0.008         Should be almost at vacume shape by now
0.0       91,900m     0.0           Final shape
~~~

**Comment by jsolson** [comment]
> is worth it to prioritize better looks in vacuum for these dedicated vac engines?

Prioritize for vacuum on those. Their sea level Isp is so poor, they would be putting out very little thrust so I wouldn't expect a very clean plume anyway.

> what do you think of following this curve for plume expansion?

I think you've got it. I would expect it to hold shape to max Q. And somewhere over 30,000 the mach shock cone will be so wide it's no longer pushing it back.

**Comment by CobaltWolf** [comment]
If you run into anything that seems straight up broken (the fxTransform being in a poor position, for example) let me know

**Comment by zorg2044** [comment]
@CobaltWolf Haven't run into anything that can be described as really broken. Just two slightly werid issues that can be fudged. 

Apart from the Agena secondary engine issue that I DM'm you yesterday (where the positioning was asymmetric), I've just now found that the vernier plumes on the JPL 6K end up different sizes. 

Like with the Agena, since they are Vac engines the issue is somewhat hidden due to the whispy plumes used though it will be apparent to anyone looking closely.


Screenshot 2019-03-31 18 54 25

Screenshot 2019-03-31 18 54 37

The 45K is fine though despite having 4 verniers (I hear there can be scaling issues with multiple transforms)

**Comment by jsolson** [comment]
> I hear there can be scaling issues with multiple transforms

I thought that wasn't an issue with Smokescreen running things. Does it still happen using one of the RealPlume prefabs?

**Comment by zorg2044** [comment]
You know what after going back and forth on it a bit, I've decided to revert all kerolox verniers I've done back to the originals as I've not managed to make a sufficient improvement. I have added the emissionmult parameter to the engine config to halve the particle count on those though. It didnt affect the look.

Re 6K engine with the original plume has the same issue as the Agena secondary ie the plume positions are asymmetric. 

Screenshot 2019-04-01 08 56 08

How it was dealt with originally. Its annoying because at least on the agena secondary the structure of the engine hides some of the clipped in plume.
Screenshot 2019-04-01 08 59 43

**Comment by zorg2044** [comment]
LR87-11 and LR91-11 conversion. I'll be honest, while the 87-11 plume design is beautiful, I feel like the LR87-5 design has a more Titan-esque feel.

Screenshot 2019-04-01 15 01 04

Screenshot 2019-04-01 15 02 12

Screenshot 2019-04-01 15 02 22

Screenshot 2019-04-01 15 02 34

Screenshot 2019-04-01 15 03 51

Screenshot 2019-04-01 15 04 04

**Comment by jsolson** [comment]
That jet engine plume on the -11 is the old one. You can toss that and use the same plume as the -5 engine.

**Comment by CobaltWolf** [comment]
I liked the blue, is there an engine that it's more appropriate on?

**Comment by jsolson** [comment]
I think I put a similar effect on Redstone

**Comment by zorg2044** [comment]
Screenshot 2019-04-02 00 54 28

current PlumeParty plumes for SL J2 and the blue plume that Cobalt likes. Let me know know if you guys would like me to use the blue LR87 one instead of the flamey one for the SL J2 when I do the conversion. 

(I havent finalized the curves on the blue plume, I will make the shock cone more prominent to match the stock one compared to the earlier pics above)

**Comment by zorg2044** [comment]
Screenshot 2019-04-02 18 21 00

Experimental hypergolic gas generator effect for LR87. I think it works even without a dedicated transform as the effect is pretty translucent and fades in from the origin point. So it looks ok even with all the part variants where the gas generator exhausts are positioned at different heights relative to the engine bell.

**Comment by jsolson** [comment]
He should be able to add an effects transform for those exhaust nozzles.

I thought the LR-87 might look a little better if the blaze effect wasn't there off the ground faded in around 3000 meters, sort of as the beginning of expansion. What do you think of this? I didn't rework the whole thing, just added two lines to emission.

~~~
@PART[*]:HAS[@PLUME[LR87HypergolicLower]]:AFTER[zRealPlume]:NEEDS[SmokeScreen]
{
  %EFFECTS
  {
    %LR87HypergolicLower
    {
          MODEL_MULTI_SHURIKEN_PERSIST
          {
              //Get the inputs from the other config.
              transformName = #$../../../PLUME[LR87HypergolicLower]/transformName$
              localRotation = #$../../../PLUME[LR87HypergolicLower]/localRotation[0]$,$../../../PLUME[LR87HypergolicLower]/localRotation[1]$,$../../../PLUME[LR87HypergolicLower]/localRotation[2]$
              localPosition = #$../../../PLUME[LR87HypergolicLower]/blazePosition[0]$,$../../../PLUME[LR87HypergolicLower]/blazePosition[1]$,$../../../PLUME[LR87HypergolicLower]/blazePosition[2]$
              fixedScale    = #$../../../PLUME[LR87HypergolicLower]/blazeScale$
              energy        = #$../../../PLUME[LR87HypergolicLower]/blazeenergy$
              speed         = #$../../../PLUME[LR87HypergolicLower]/blazespeed$
              emissionMult  = #$../../../PLUME[LR87HypergolicLower]/blazeemissionMult$
              //
              name = blaze
              modelName = Bluedog_DB/FX/PlumeParty/Engines/BDB/TitanSLBlaze

.. snip ..

              emission
              {
                density = 1.0 0 // <-----
		density = 0.9 0 // <-----
                density = 0.5 2
                density = 0.4 1
                density = 0.35 0
                density = 0.1 0
                density = 0.05 0
                density = 0.0 0
                power = 1 1
                power = 0.01 0.2
                power = 0 0
              }
~~~

**Comment by zorg2044** [comment]
Cool I'll take a look later today! 

About the Titan gas generator cobalt saw the pics and hes not so sure about the look. Thought I would just preview it here as food for thought.

Sea level J2 and Aerospike testing.

The aerospike plume is bascially the blue jet plume but with a flame core added on at lift off (inspired by the pic of the actual test firing cobalt sent me)

Screenshot 2019-04-02 19 36 10


Screenshot 2019-04-02 19 42 46


Screenshot 2019-04-02 19 36 57

Screenshot 2019-04-02 19 38 22

**Comment by zorg2044** [comment]
@jsolson the fade in fade out for the flames looks pretty good! I think we should keep it. Adds an extra phase to the plume evolution for users to enjoy too. I might try it with the J2 SL plume too although I want to keep the flame core even at SL for the aerospike based on the sea level test firing pic.

The hypergolic vernier effect from Jade is now ready, I'll try it out later today. I think most of the liquid engines have had a first pass on them now, although still needs some testing, tweaks and maybe sound volume adjustments in some cases.

I've had a first attempt at making a lower solid plume and it looks very challenging. The current solid plumes in real plume use trailing smoke effects and are configured very very differently to everything else. Copying the curves outright and tweaking them hasn't worked out for me with Jades trails unfortunately :(

Experimentation and building the effect from scratch is difficult as I need to have the engine in motion to see how the smoke behaves with trail smoke, I cant just leave it on the pad like I normally do. If I dont make a breakthrough we may have to limit the scope of this project to just liquid engines for now (and perhaps upper solids like the star series).

I could do solid plumes with non trailing smoke even now I think, it would offer better performance particle wise for sure as the RealPlume solids are very heavy on particle count. However, in terms of looks it would be a downgrade as RealPlumes smoke trails look downright epic.

**Comment by jsolson** [comment]
Ok to merge?

Solids are kind of all about the smoke. With stock effects we want to watch the framerates. With RealPlume we can assume high end pc and definitely want epic over performance.

**Comment by zorg2044** [comment]
@jsolson I think this will be in a position to merge around the weekend. I'll clean up the sound fx, still need to add the hypergolic vernier and add plumes to the Athena OAM and a few others that slipped by, and some testing to make sure its all good!

**Comment by jsolson** [comment]
Ah, Houston, we have a problem...

`@PART[bluedog_agenaSecondaryEngine]:HAS[@PLUME[LR91HypergolicVernier]]:FOR[zzRealPlume]`

We can't do `:FOR[zzRealPlume]`. If `:AFTER[zRealPlume]` won't suffice, we'll have to use `:FOR[zzzBluedog_DB]`.

I realize it's not the same thing, but there's been endless issues with mods using the `:FOR[RealPlume]` syntax (that's why we do the `NEEDS[zRealPlume]` test instead of `NEEDS[RealPlume]`), and I don't want to encourage bad behavior.

**Comment by zorg2044** [comment]
@jsolson Ah ok I'll correct it. The syntax of the patch actually came from NHawks (who maintains RealPlume stock configs) when I was trying to do some volume adjustments some time back so I had assumed it was kosher. I'll change it to :AFTER[zRealPlume], dont see why it shouldnt work.

**Comment by zorg2044** [comment]
hey @jsolson , I think this PR is good to go now. All the liquid engines should be covered now. I've not noticed any issues in testing so far either. I've left all the solids and monoprop based engines as they were, will open a new PR for any new Titan engines as they come.

I have added gas generators to a number of engines, cleaner ones for hypergols like Agena and using the smokier effects for various kerolox engines. The H1D has been given the F1 turbo effect as well (its quite subtle though).

Screenshot 2019-04-06 12 20 41

The gas generator has been removed from the Lr87s after consulting with Cobalt. 

The MM syntax for extra effects and volume adjustments have been corrected as well, sound rocket mini has been replaced.

**Comment by jsolson** [comment]
Good job. I'm going to put you in for a medal.

**Pull request merged**
